### PR TITLE
VIMC-4734 Add comments to responsibilities

### PR DESCRIPTION
**Pull request by mwoodbri**

### CODE REVIEW

**Review by EmmaLRussell — APPROVED** [review]

**Comment by mwoodbri** [comment]
Changes since last review:
* Make relevant `ResponsibilityComment` fields optional so that it can be used for both GET and POST

**Review by EmmaLRussell — COMMENTED** [review]
This is so that the POSTed comment body can be `{"comment": "some comment"}`?

It sort of feels  to me like they  really are two different models - it's not that `added_by` and `added_on` are optional within the same usage of the model (e.g. like the list of reports where some have missing 'date' field if they've never been run) . the added fields will always be present on GET and never on POST. I appreciate that the documented schema reflects this, but it just means the code is a little misleading. 

Would it be too tiresome to have something like ResponsibilityComment and ResponsibilityCommentPayload?

**Comment by mwoodbri** [comment]
> Would it be too tiresome to have something like ResponsibilityComment and ResponsibilityCommentPayload?

Not at all - will fix. Good suggestion.

**Comment by mwoodbri** [comment]
> > Would it be too tiresome to have something like ResponsibilityComment and ResponsibilityCommentPayload?
> 
> Not at all - will fix. Good suggestion.

See e7923ef3

**Pull request merged**
